[package]
name = "splr"
version = "0.0.11"
authors = ["shujinarazaki <shujinarazaki@protonmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
