[package]
name = "splr"
version = "0.1.0"
authors = ["Shuji Narazaki <shujinarazaki@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.14"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
